const STUDENT_CARD_STATUS = {
    ALL: 0,
    SELECTED: 1,
    IN_PROGRESS: 2,
    COMPLETED: 3,
    ABANDONED: 4
};

const MILESTONE_STATUS = {
    ACTIVE: 1,
    COMPLETED: 2,
    LATE: 3,
    PLANNED: 4,
    DELETED: 5
};

export { STUDENT_CARD_STATUS, MILESTONE_STATUS };
